[build]
builder = "nixpacks"
buildCommand = "npm install --prefix server && npm install --prefix client && npm run build"

[deploy]
startCommand = "npm run start --prefix server"
restartPolicyType = "on_failure"
